version: '3'
services:
    web:
        build: .
        image: vijos/vj4
        restart: always
        command: vj4.server
        env_file: .env
        volumes:
            - "./data/run:/var/run/vj4"
        links:
            - mongodb
            - rabbitmq
        ports: [ "8888:8888" ]
        depends_on:
            - rabbitmq
            - mongodb

    # Before uncomment these lines, you should have created necessary files
    # like config.yaml for it.
    # See README.md for instructions.
    #-------------------------------------------------------------------------------
    #judge:
    #    restart: always
    #    privileged: true
    #    image: vijos/jd4
    #    volumes:
    #        - "./data/judge/config.yaml:/root/.config/jd4/config.yaml"
    #        - "./data/judge/cache:/root/.cache/jd4"
    #    links:
    #        - web
    #        # - web_backend # uncomment this only if you have this service

    # You can uncomment this block to enable a internal only web service.
    # Consider to use this if your main web service is listening to a unix socket.
    # For example, you can set your judge connect to `http://web_backend:8787`.
    #-------------------------------------------------------------------------------
    #web_backend:
    #    image: vijos/vj4
    #    restart: always
    #    command: vj4.server
    #    env_file: .env
    #    environment: # this will override env in `env_file`
    #        VJ_LISTEN: "http://0.0.0.0:8787"
    #    # ports: 
    #    #     - "8787:8787"
    #    links:
    #        - rabbitmq
    #        - mongodb
    #    depends_on:
    #        - rabbitmq
    #        - mongodb

    rabbitmq:
        restart: always
        image: rabbitmq:latest
        volumes:
            - "./data/rabbitmq:/var/lib/rabbitmq"

    mongodb:
        restart: always
        image: mongo:latest
        volumes:
            - "./data/mongodb:/data/db"
